name: Dispatch Preview Update
on:
  push:
    branches: [development]

jobs:
  dispatch:
    runs-on: ubuntu-18.04
    steps:
      - run: >-
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.TOKEN }}" --data '{"event_type": "pull"}' https://api.github.com/repos/CHTC/article-preview/dispatches
